apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ghq18qy2j-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:d31ea7b39a96a18fcb90a5938a7d28afbc0db5c1@sha256:a74c1da85e99775b9834bb0fe6f5fc460d580f0d955fc5f9e047768ee4190cb2
          name: container-image
