apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ghq18qy2j-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ghq18qy2j-dotnet-basic-gitops